# MyBatis Plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field:  isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true

    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.jovan.usercenter.mapper
  # 指定mapper xml文件位置（如果有的话）
  mapper-locations: classpath*:mapper/**/*.xml

# 应用服务 WEB 访问端口
server:
  port: 8080

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jov-user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # session失效时间
  session:
    timeout: 86400