
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user_center
    password: 123456
  # session失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
